const ABREVIACOES = {
  // GÊNESIS
  "gn": "genesis",
  "ge": "genesis",
  "gen": "genesis",
  "Gen": "genesis",
  "GEN": "genesis",
  "Gên": "genesis",
  "Gên.": "genesis",
  "gên": "genesis",
  "Gênesis": "genesis",
  "gênesis": "genesis",
  "genesis": "genesis",
  "Genesis": "genesis",
  
  // ÊXODO
  "ex": "exodo",
  "êx": "exodo",
  "exo": "exodo",
  "Exo": "exodo",
  "EXO": "exodo",
  "Êxo": "exodo",
  "Êxo.": "exodo",
  "êxo": "exodo",
  "Êxodo": "exodo",
  "êxodo": "exodo",
  "exodo": "exodo",
  "Exodo": "exodo",
  
  // LEVÍTICO
  "lv": "levitico",
  "le": "levitico",
  "lev": "levitico",
  "Lev": "levitico",
  "LEV": "levitico",
  "Lev.": "levitico",
  "Levítico": "levitico",
  "levítico": "levitico",
  "levitico": "levitico",
  "Levitico": "levitico",
  
  // NÚMEROS
  "nm": "numeros",
  "nu": "numeros",
  "num": "numeros",
  "Num": "numeros",
  "NUM": "numeros",
  "Núm": "numeros",
  "Núm.": "numeros",
  "núm": "numeros",
  "Números": "numeros",
  "números": "numeros",
  "numeros": "numeros",
  "Numeros": "numeros",
  
  // DEUTERONÔMIO
  "dt": "deuteronomio",
  "de": "deuteronomio",
  "deu": "deuteronomio",
  "Deu": "deuteronomio",
  "DEU": "deuteronomio",
  "Deu.": "deuteronomio",
  "Deuteronômio": "deuteronomio",
  "deuteronômio": "deuteronomio",
  "deuteronomio": "deuteronomio",
  "Deuteronomio": "deuteronomio",
  
  // JOSUÉ
  "js": "josue",
  "jos": "josue",
  "Jos": "josue",
  "JOS": "josue",
  "Jos.": "josue",
  "Josué": "josue",
  "josué": "josue",
  "josue": "josue",
  "Josue": "josue",
  
  // JUÍZES
  "jz": "juizes",
  "ju": "juizes",
  "jui": "juizes",
  "Jui": "juizes",
  "JUI": "juizes",
  "Juí": "juizes",
  "Juí.": "juizes",
  "juí": "juizes",
  "Juízes": "juizes",
  "juízes": "juizes",
  "juizes": "juizes",
  "Juizes": "juizes",
  
  // RUTE
  "rt": "rute",
  "ru": "rute",
  "rut": "rute",
  "Rut": "rute",
  "RUT": "rute",
  "Rut.": "rute",
  "Rute": "rute",
  "rute": "rute",
  
  // 1 SAMUEL
  "1s": "1samuel",
  "1sm": "1samuel",
  "1Sam": "1samuel",
  "1SAM": "1samuel",
  "1sam": "1samuel",
  "1 Sam": "1samuel",
  "1 Sam.": "1samuel",
  "1 Samuel": "1samuel",
  "1Samuel": "1samuel",
  "1samuel": "1samuel",
  
  // 2 SAMUEL
  "2s": "2samuel",
  "2sm": "2samuel",
  "2Sam": "2samuel",
  "2SAM": "2samuel",
  "2sam": "2samuel",
  "2 Sam": "2samuel",
  "2 Sam.": "2samuel",
  "2 Samuel": "2samuel",
  "2Samuel": "2samuel",
  "2samuel": "2samuel",
  
  // 1 REIS
  "1r": "1reis",
  "1rs": "1reis",
  "1Re": "1reis",
  "1RE": "1reis",
  "1re": "1reis",
  "1Reis": "1reis",
  "1REIS": "1reis",
  "1reis": "1reis",
  "1 Reis": "1reis",
  "1 Re": "1reis",
  
  // 2 REIS
  "2r": "2reis",
  "2rs": "2reis",
  "2Re": "2reis",
  "2RE": "2reis",
  "2re": "2reis",
  "2Reis": "2reis",
  "2REIS": "2reis",
  "2reis": "2reis",
  "2 Reis": "2reis",
  "2 Re": "2reis",
  
  // 1 CRÔNICAS
  "1c": "1cronicas",
  "1cr": "1cronicas",
  "1Cr": "1cronicas",
  "1CR": "1cronicas",
  "1cro": "1cronicas",
  "1Cro": "1cronicas",
  "1CRO": "1cronicas",
  "1crô": "1cronicas",
  "1Crô": "1cronicas",
  "1CRÔ": "1cronicas",
  "1 Cr": "1cronicas",
  "1 Crô": "1cronicas",
  "1 Crô.": "1cronicas",
  "1 Crônicas": "1cronicas",
  "1Cronicas": "1cronicas",
  "1CRONICAS": "1cronicas",
  "1cronicas": "1cronicas",
  
  // 2 CRÔNICAS
  "2c": "2cronicas",
  "2cr": "2cronicas",
  "2Cr": "2cronicas",
  "2CR": "2cronicas",
  "2cro": "2cronicas",
  "2Cro": "2cronicas",
  "2CRO": "2cronicas",
  "2crô": "2cronicas",
  "2Crô": "2cronicas",
  "2CRÔ": "2cronicas",
  "2 Cr": "2cronicas",
  "2 Crô": "2cronicas",
  "2 Crô.": "2cronicas",
  "2 Crônicas": "2cronicas",
  "2Cronicas": "2cronicas",
  "2CRONICAS": "2cronicas",
  "2cronicas": "2cronicas",
  
  // ESDRAS
  "ed": "esdras",
  "es": "esdras",
  "esd": "esdras",
  "Esd": "esdras",
  "ESD": "esdras",
  "Esd.": "esdras",
  "Esdras": "esdras",
  "esdras": "esdras",
  
  // NEEMIAS
  "ne": "neemias",
  "nee": "neemias",
  "Nee": "neemias",
  "NEE": "neemias",
  "Nee.": "neemias",
  "Neemias": "neemias",
  "neemias": "neemias",
  
  // ESTER
  "et": "ester",
  "est": "ester",
  "Est": "ester",
  "EST": "ester",
  "Est.": "ester",
  "Ester": "ester",
  "ester": "ester",
  
  // JÓ
  "jó": "jo",
  "job": "jo",
  "Job": "jo",
  "JOB": "jo",
  "Jó": "jo",
  "JÓ": "jo",
  "jo": "jo",
  "Jo": "jo",
  "JO": "jo",
  
  // SALMOS
  "sl": "salmos",
  "sa": "salmos",
  "sal": "salmos",
  "Sal": "salmos",
  "SAL": "salmos",
  "Sal.": "salmos",
  "Salmos": "salmos",
  "salmos": "salmos",
  "Salmo": "salmos",
  "salmo": "salmos",
  
  // PROVÉRBIOS
  "pv": "proverbios",
  "pr": "proverbios",
  "pro": "proverbios",
  "Pro": "proverbios",
  "PRO": "proverbios",
  "Prov": "proverbios",
  "PROV": "proverbios",
  "prov": "proverbios",
  "Prov.": "proverbios",
  "Provérbios": "proverbios",
  "provérbios": "proverbios",
  "proverbios": "proverbios",
  "Proverbios": "proverbios",
  
  // ECLESIASTES
  "ec": "eclesiastes",
  "ecl": "eclesiastes",
  "Ecl": "eclesiastes",
  "ECL": "eclesiastes",
  "Ecl.": "eclesiastes",
  "Eclesiastes": "eclesiastes",
  "eclesiastes": "eclesiastes",
  
  // CÂNTICO DE SALOMÃO
  "ct": "cantico",
  "cn": "cantico",
  "can": "cantico",
  "Can": "cantico",
  "CAN": "cantico",
  "Cânt": "cantico",
  "CÂNT": "cantico",
  "cânt": "cantico",
  "Cânt.": "cantico",
  "Cântico": "cantico",
  "cântico": "cantico",
  "cantico": "cantico",
  "Cantico": "cantico",
  "Cântico de Salomão": "cantico",
  "Cantares": "cantico",
  "cantares": "cantico",
  
  // ISAÍAS
  "is": "isaias",
  "isa": "isaias",
  "Isa": "isaias",
  "ISA": "isaias",
  "Isa.": "isaias",
  "Isaías": "isaias",
  "isaías": "isaias",
  "isaias": "isaias",
  "Isaias": "isaias",
  
  // JEREMIAS
  "jr": "jeremias",
  "je": "jeremias",
  "jer": "jeremias",
  "Jer": "jeremias",
  "JER": "jeremias",
  "Jer.": "jeremias",
  "Jeremias": "jeremias",
  "jeremias": "jeremias",
  
  // LAMENTAÇÕES
  "lm": "lamentacoes",
  "la": "lamentacoes",
  "lam": "lamentacoes",
  "Lam": "lamentacoes",
  "LAM": "lamentacoes",
  "Lam.": "lamentacoes",
  "Lamentações": "lamentacoes",
  "lamentações": "lamentacoes",
  "lamentacoes": "lamentacoes",
  "Lamentacoes": "lamentacoes",
  
  // EZEQUIEL
  "ez": "ezequiel",
  "eze": "ezequiel",
  "Eze": "ezequiel",
  "EZE": "ezequiel",
  "Eze.": "ezequiel",
  "Ezequiel": "ezequiel",
  "ezequiel": "ezequiel",
  
  // DANIEL
  "dn": "daniel",
  "da": "daniel",
  "dan": "daniel",
  "Dan": "daniel",
  "DAN": "daniel",
  "Dan.": "daniel",
  "Daniel": "daniel",
  "daniel": "daniel",
  
  // OSEIAS
  "os": "oseias",
  "Os": "oseias",
  "OS": "oseias",
  "Osé": "oseias",
  "OSÉ": "oseias",
  "osé": "oseias",
  "Osé.": "oseias",
  "Ose.": "oseias",
  "Ose": "oseias",
  "OSE.": "oseias",
  "OSE": "oseias",
  "Oseias": "oseias",
  "oseias": "oseias",
  "Oseías": "oseias",
  "oseías": "oseias",
  
  // JOEL
  "jl": "joel",
  "joel": "joel",
  "Joel": "joel",
  "JOEL": "joel",
  "Joel.": "joel",
  
  // AMÓS
  "am": "amos",
  "Am": "amos",
  "AM": "amos",
  "Amós": "amos",
  "AMÓS": "amos",
  "amós": "amos",
  "Amós.": "amos",
  "amos": "amos",
  "Amos": "amos",
  
  // OBADIAS
  "ob": "obadias",
  "Ob": "obadias",
  "OB": "obadias",
  "Oba": "obadias",
  "OBA": "obadias",
  "oba": "obadias",
  "Oba.": "obadias",
  "Obadias": "obadias",
  "obadias": "obadias",
  
  // JONAS
  "jn": "jonas",
  "jon": "jonas",
  "Jon": "jonas",
  "JON": "jonas",
  "Jon.": "jonas",
  "Jonas": "jonas",
  "jonas": "jonas",
  
  // MIQUEIAS
  "mq": "miqueias",
  "mi": "miqueias",
  "miq": "miqueias",
  "Miq": "miqueias",
  "MIQ": "miqueias",
  "Miq.": "miqueias",
  "Miquéias": "miqueias",
  "miquéias": "miqueias",
  "miqueias": "miqueias",
  "Miqueias": "miqueias",
  
  // NAUM
  "na": "naum",
  "Na": "naum",
  "NA": "naum",
  "Naum": "naum",
  "NAUM": "naum",
  "naum": "naum",
  "Naum.": "naum",
  
  // HABACUQUE
  "hb": "habacuque",
  "ha": "habacuque",
  "hab": "habacuque",
  "Hab": "habacuque",
  "HAB": "habacuque",
  "Hab.": "habacuque",
  "Habacuque": "habacuque",
  "habacuque": "habacuque",
  
  // SOFONIAS
  "sf": "sofonias",
  "so": "sofonias",
  "Sof": "sofonias",
  "SOF": "sofonias",
  "sof": "sofonias",
  "Sof.": "sofonias",
  "Sofonias": "sofonias",
  "sofonias": "sofonias",
  
  // AGEU
  "ag": "ageu",
  "Ag": "ageu",
  "AG": "ageu",
  "Ageu": "ageu",
  "AGEU": "ageu",
  "ageu": "ageu",
  "Ageu.": "ageu",
  
  // ZACARIAS
  "zc": "zacarias",
  "za": "zacarias",
  "zac": "zacarias",
  "Zac": "zacarias",
  "ZAC": "zacarias",
  "Zac.": "zacarias",
  "Zacarias": "zacarias",
  "zacarias": "zacarias",
  
  // MALAQUIAS
  "ml": "malaquias",
  "ma": "malaquias",
  "mal": "malaquias",
  "Mal": "malaquias",
  "MAL": "malaquias",
  "Mal.": "malaquias",
  "Malaquias": "malaquias",
  "malaquias": "malaquias",
  
  // MATEUS
  "mt": "mateus",
  "mat": "mateus",
  "Mat": "mateus",
  "MAT": "mateus",
  "Mat.": "mateus",
  "Mateus": "mateus",
  "mateus": "mateus",
  
  // MARCOS
  "mc": "marcos",
  "mr": "marcos",
  "mar": "marcos",
  "Mar": "marcos",
  "MAR": "marcos",
  "Mar.": "marcos",
  "Marcos": "marcos",
  "marcos": "marcos",
  
  // LUCAS
  "lc": "lucas",
  "lu": "lucas",
  "luc": "lucas",
  "Luc": "lucas",
  "LUC": "lucas",
  "Luc.": "lucas",
  "Lucas": "lucas",
  "lucas": "lucas",
  
  // JOÃO
  "jo": "joao",
  "jã": "joao",
  "joa": "joao",
  "Joa": "joao",
  "JOA": "joao",
  "Joã": "joao",
  "JOÃ": "joao",
  "joã": "joao",
  "Joã.": "joao",
  "João": "joao",
  "JOÃO": "joao",
  "joão": "joao",
  "joao": "joao",
  "Joao": "joao",
  
  // ATOS
  "at": "atos",
  "ato": "atos",
  "Ato": "atos",
  "ATO": "atos",
  "Atos": "atos",
  "ATOS": "atos",
  "atos": "atos",
  "Atos.": "atos",
  
  // ROMANOS
  "rm": "romanos",
  "ro": "romanos",
  "rom": "romanos",
  "Rom": "romanos",
  "ROM": "romanos",
  "Rom.": "romanos",
  "Romanos": "romanos",
  "romanos": "romanos",
  
  // 1 CORÍNTIOS

  "1co": "1corintios",
  "1Co": "1corintios",
  "1CO": "1corintios",
  "1Cor": "1corintios",
  "1COR": "1corintios",
  "1cor": "1corintios",
  "1 Co": "1corintios",
  "1 Cor": "1corintios",
  "1 Cor.": "1corintios",
  "1 Coríntios": "1corintios",
  "1Corintios": "1corintios",
  "1CORINTIOS": "1corintios",
  "1corintios": "1corintios",
  
  // 2 CORÍNTIOS
  "2co": "2corintios",
  "2Co": "2corintios",
  "2CO": "2corintios",
  "2Cor": "2corintios",
  "2COR": "2corintios",
  "2cor": "2corintios",
  "2 Co": "2corintios",
  "2 Cor": "2corintios",
  "2 Cor.": "2corintios",
  "2 Coríntios": "2corintios",
  "2Corintios": "2corintios",
  "2CORINTIOS": "2corintios",
  "2corintios": "2corintios",
  
  // GÁLATAS
  "gl": "galatas",
  "ga": "galatas",
  "gal": "galatas",
  "Gal": "galatas",
  "GAL": "galatas",
  "Gál": "galatas",
  "GÁL": "galatas",
  "gál": "galatas",
  "Gál.": "galatas",
  "Gálatas": "galatas",
  "gálatas": "galatas",
  "galatas": "galatas",
  "Galatas": "galatas",
  
  // EFÉSIOS
  "ef": "efesios",
  "efe": "efesios",
  "Efe": "efesios",
  "EFE": "efesios",
  "Efé": "efesios",
  "EFÉ": "efesios",
  "efé": "efesios",
  "Efé.": "efesios",
  "Efésios": "efesios",
  "efésios": "efesios",
  "efesios": "efesios",
  "Efesios": "efesios",
  
  // FILIPENSES
  "fp": "filipenses",
  "fi": "filipenses",
  "fil": "filipenses",
  "Fil": "filipenses",
  "FIL": "filipenses",
  "Fil.": "filipenses",
  "Filipenses": "filipenses",
  "filipenses": "filipenses",
  
  // COLOSSENSES
  "cl": "colossenses",
  "co": "colossenses",
  "col": "colossenses",
  "Col": "colossenses",
  "COL": "colossenses",
  "Col.": "colossenses",
  "Colossenses": "colossenses",
  "colossenses": "colossenses",
  
  // 1 TESSALONICENSES
  "1ts": "1tessalonicenses",
  "1Ts": "1tessalonicenses",
  "1TS": "1tessalonicenses",
  "1te": "1tessalonicenses",
  "1Te": "1tessalonicenses",
  "1TE": "1tessalonicenses",
  "1tes": "1tessalonicenses",
  "1Tes": "1tessalonicenses",
  "1TES": "1tessalonicenses",
  "1 Ts": "1tessalonicenses",
  "1 Tes": "1tessalonicenses",
  "1 Tes.": "1tessalonicenses",
  "1 Tessalonicenses": "1tessalonicenses",
  "1Tessalonicenses": "1tessalonicenses",
  "1TESSALONICENSES": "1tessalonicenses",
  "1tessalonicenses": "1tessalonicenses",
  
  // 2 TESSALONICENSES
  "2ts": "2tessalonicenses",
  "2Ts": "2tessalonicenses",
  "2TS": "2tessalonicenses",
  "2te": "2tessalonicenses",
  "2Te": "2tessalonicenses",
  "2TE": "2tessalonicenses",
  "2tes": "2tessalonicenses",
  "2Tes": "2tessalonicenses",
  "2TES": "2tessalonicenses",
  "2 Ts": "2tessalonicenses",
  "2 Tes": "2tessalonicenses",
  "2 Tes.": "2tessalonicenses",
  "2 Tessalonicenses": "2tessalonicenses",
  "2Tessalonicenses": "2tessalonicenses",
  "2TESSALONICENSES": "2tessalonicenses",
  "2tessalonicenses": "2tessalonicenses",
  
  // 1 TIMÓTEO
  "1tm": "1timoteo",
  "1Tm": "1timoteo",
  "1TM": "1timoteo",
  "1ti": "1timoteo",
  "1Ti": "1timoteo",
  "1TI": "1timoteo",
  "1tim": "1timoteo",
  "1Tim": "1timoteo",
  "1TIM": "1timoteo",
  "1 Tm": "1timoteo",
  "1 Tim": "1timoteo",
  "1 Tim.": "1timoteo",
  "1 Timóteo": "1timoteo",
  "1Timoteo": "1timoteo",
  "1TIMOTEO": "1timoteo",
  "1timoteo": "1timoteo",
  
  // 2 TIMÓTEO
  "2tm": "2timoteo",
  "2Tm": "2timoteo",
  "2TM": "2timoteo",
  "2ti": "2timoteo",
  "2Ti": "2timoteo",
  "2TI": "2timoteo",
  "2tim": "2timoteo",
  "2Tim": "2timoteo",
  "2TIM": "2timoteo",
  "2 Tm": "2timoteo",
  "2 Tim": "2timoteo",
  "2 Tim.": "2timoteo",
  "2 Timóteo": "2timoteo",
  "2Timoteo": "2timoteo",
  "2TIMOTEO": "2timoteo",
  "2timoteo": "2timoteo",
  
  // TITO
  "tt": "tito",
  "tit": "tito",
  "Tit": "tito",
  "TIT": "tito",
  "Tito": "tito",
  "TITO": "tito",
  "tito": "tito",
  "Tito.": "tito",
  
  // FILEMOM
  "fm": "filemon",
  "fl": "filemon",
  "flm": "filemon",
  "Flm": "filemon",
  "FLM": "filemon",
  "Flm.": "filemon",
  "Filemon": "filemon",
  "filemon": "filemon",
  
  // HEBREUS
  "he": "hebreus",
  "heb": "hebreus",
  "Heb": "hebreus",
  "HEB": "hebreus",
  "Heb.": "hebreus",
  "Hebreus": "hebreus",
  "hebreus": "hebreus",
  
  // TIAGO
  "tg": "tiago",
  "tia": "tiago",
  "Tia": "tiago",
  "TIA": "tiago",
  "Tia.": "tiago",
  "Tiago": "tiago",
  "tiago": "tiago",
  
  // 1 PEDRO
  "1p": "1pedro",
  "1pe": "1pedro",
  "1Pe": "1pedro",
  "1PE": "1pedro",
  "1ped": "1pedro",
  "1Ped": "1pedro",
  "1PED": "1pedro",
  "1 P": "1pedro",
  "1 Pe": "1pedro",
  "1 Ped": "1pedro",
  "1 Ped.": "1pedro",
  "1 Pedro": "1pedro",
  "1Pedro": "1pedro",
  "1PEDRO": "1pedro",
  "1pedro": "1pedro",
  
  // 2 PEDRO
  "2p": "2pedro",
  "2pe": "2pedro",
  "2Pe": "2pedro",
  "2PE": "2pedro",
  "2ped": "2pedro",
  "2Ped": "2pedro",
  "2PED": "2pedro",
  "2 P": "2pedro",
  "2 Pe": "2pedro",
  "2 Ped": "2pedro",
  "2 Ped.": "2pedro",
  "2 Pedro": "2pedro",
  "2Pedro": "2pedro",
  "2PEDRO": "2pedro",
  "2pedro": "2pedro",
  
  // 1 JOÃO
  "1j": "1joao",
  "1jo": "1joao",
  "1Jo": "1joao",
  "1JO": "1joao",
  "1jã": "1joao",
  "1Jã": "1joao",
  "1JÃ": "1joao",
  "1joa": "1joao",
  "1Joa": "1joao",
  "1JOA": "1joao",
  "1joã": "1joao",
  "1Joã": "1joao",
  "1JOÃ": "1joao",
  "1 J": "1joao",
  "1 Jo": "1joao",
  "1 Joã": "1joao",
  "1 Joã.": "1joao",
  "1 João": "1joao",
  "1João": "1joao",
  "1JOÃO": "1joao",
  "1joão": "1joao",
  "1joao": "1joao",
  "1Joao": "1joao",
  
  // 2 JOÃO
  "2j": "2joao",
  "2jo": "2joao",
  "2Jo": "2joao",
  "2JO": "2joao",
  "2jã": "2joao",
  "2Jã": "2joao",
  "2JÃ": "2joao",
  "2joa": "2joao",
  "2Joa": "2joao",
  "2JOA": "2joao",
  "2joã": "2joao",
  "2Joã": "2joao",
  "2JOÃ": "2joao",
  "2 J": "2joao",
  "2 Jo": "2joao",
  "2 Joã": "2joao",
  "2 Joã.": "2joao",
  "2 João": "2joao",
  "2João": "2joao",
  "2JOÃO": "2joao",
  "2joão": "2joao",
  "2joao": "2joao",
  "2Joao": "2joao",
  
  // 3 JOÃO
  "3j": "3joao",
  "3jo": "3joao",
  "3Jo": "3joao",
  "3JO": "3joao",
  "3jã": "3joao",
  "3Jã": "3joao",
  "3JÃ": "3joao",
  "3joa": "3joao",
  "3Joa": "3joao",
  "3JOA": "3joao",
  "3joã": "3joao",
  "3Joã": "3joao",
  "3JOÃ": "3joao",
  "3 J": "3joao",
  "3 Jo": "3joao",
  "3 Joã": "3joao",
  "3 Joã.": "3joao",
  "3 João": "3joao",
  "3João": "3joao",
  "3JOÃO": "3joao",
  "3joão": "3joao",
  "3joao": "3joao",
  "3Joao": "3joao",
  
  // JUDAS
  "jd": "judas",
  "jud": "judas",
  "Jud": "judas",
  "JUD": "judas",
  "Judas": "judas",
  "JUDAS": "judas",
  "judas": "judas",
  "Judas.": "judas",
  
  // APOCALIPSE
  "ap": "apocalipse",
  "apo": "apocalipse",
  "Apo": "apocalipse",
  "APO": "apocalipse",
  "Apo.": "apocalipse",
  "apoc": "apocalipse",
  "Apoc": "apocalipse",
  "APOC": "apocalipse",
  "Apoc.": "apocalipse",
  "Apocalipse": "apocalipse",
  "apocalipse": "apocalipse",
  "Revelação": "apocalipse",
  "revelação": "apocalipse",
  "revelacao": "apocalipse",
  "Revelacao": "apocalipse"
};